require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/policemen", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Policeman. As you add validations to Policeman, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Policeman.create! valid_attributes
      get policemen_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      policeman = Policeman.create! valid_attributes
      get policeman_url(policeman)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_policeman_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      policeman = Policeman.create! valid_attributes
      get edit_policeman_url(policeman)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Policeman" do
        expect {
          post policemen_url, params: { policeman: valid_attributes }
        }.to change(Policeman, :count).by(1)
      end

      it "redirects to the created policeman" do
        post policemen_url, params: { policeman: valid_attributes }
        expect(response).to redirect_to(policeman_url(Policeman.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Policeman" do
        expect {
          post policemen_url, params: { policeman: invalid_attributes }
        }.to change(Policeman, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post policemen_url, params: { policeman: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested policeman" do
        policeman = Policeman.create! valid_attributes
        patch policeman_url(policeman), params: { policeman: new_attributes }
        policeman.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the policeman" do
        policeman = Policeman.create! valid_attributes
        patch policeman_url(policeman), params: { policeman: new_attributes }
        policeman.reload
        expect(response).to redirect_to(policeman_url(policeman))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        policeman = Policeman.create! valid_attributes
        patch policeman_url(policeman), params: { policeman: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested policeman" do
      policeman = Policeman.create! valid_attributes
      expect {
        delete policeman_url(policeman)
      }.to change(Policeman, :count).by(-1)
    end

    it "redirects to the policemen list" do
      policeman = Policeman.create! valid_attributes
      delete policeman_url(policeman)
      expect(response).to redirect_to(policemen_url)
    end
  end
end
